### ISSUE TITLE
Improve how to deal with Pagination

### ISSUE THREAD

**Issue by browniebroke** [browniebroke/deezer-python#137]
The way we deal with pagination is a bit divided between the `get_...s` and `iter_...s` methods, which caused some usage issues (see #126 and #127).

We should aim at unifying these 2 type of methods to reduce this confusion. We could either switch the `get_...s` to iterate over all the pages by default but it might cause some unexpected API consumption to the users.

I recently came across another option while using [PyGithub](https://github.com/PyGithub/PyGithub) and I liked how they [do it](https://pygithub.readthedocs.io/en/latest/utilities.html#pagination).

Their solution is to return a `PaginatedResult`. It transparently iterate through the pages if you consume it in a for loop while also letting you get a specific page or the total count of elements in the result set.

This would be a breaking change, so we can update the `get_...s` methods and remove the `iter_...s` in one go.

**Comment by lejcestlesang** [comment]
Hello. Still no updates on the issue ?

**Comment by browniebroke** [comment]
Not as far as I know.

**Comment by lejcestlesang** [comment]
I am trying to use the workaround described in the issue #126 but I am struggling to understand the change in the code. There are a lost of new methods. Should I implement them or is there a quick workaround ?
