### ISSUE TITLE
Merge workflows running on pull requests into a CI one

### ISSUE THREAD

**Issue by browniebroke** [browniebroke/deezer-python#164]
We have 4 workflows that run during CI at the moment: `test.yml`, `docs.yml`, `lint.yml` and `commitlint.yml`. We could simplify this by merging them into a single `ci.yml` workflow, with a separate job for each.

**Comment by naveen521kk** [comment]
I will take it up. Should this mean that all the files mentioned should be made into one single file `ci.yml`?
