### ISSUE TITLE
Drop support for Python 3.5

### ISSUE THREAD

**Issue by browniebroke** [browniebroke/deezer-python#166]
Python 3.5 will reach its EOL at the end of September 2020, we can drop support for it.

https://www.python.org/dev/peps/pep-0478/

**Comment by naveen521kk** [comment]
I will work on this. Changing the `setup.cfg` and configuring test would be enough right?

**Comment by browniebroke** [comment]
Yes I think it's in a few places:

- setup.cfg
- ci.yml
- tox.ini
- requirements.in can be simplified by removing `python_version > '3.5'` e.g.: 
  https://github.com/browniebroke/deezer-python/blob/a605166abb630f2ca7697014bb480f8b3977c9f3/requirements.in#L5

This will be a breaking change so ideally should be [flagged as such](https://www.conventionalcommits.org) in the commit message. It's "nice to have" though, worst case I can do it when merging.

**Comment by naveen521kk** [comment]
Will work on it in an hour or two.
