### ISSUE TITLE
names as track arguments

### ISSUE THREAD

**Issue by patalanov** [browniebroke/deezer-python#17]
I know that you can pass a `track id` as an argument to `get_track( ) `

but can I do it the other way around?

for example: retrieve `track_ids`  and streamable `urls` after passing `track names`?

**Comment by pfouque** [comment]
Why not using "search" ?

Because what you're a speaking about is a "[search](http://deezer-python.readthedocs.io/client.html#deezer.client.Client.search)" action.

You can use "relation" parameter to retrieve only tracks

`search(query, relation='track)`

**Comment by k33k00** [comment]
@patalanov Out of curiosity what happens when there are more than one track with the same name? Would it pull a list or just select the one at the top of the list?

**Comment by browniebroke** [comment]
Yes, the search API should let you do that. Getting a track just by name is not enough, you're likely will have multiple matches from different artists:

```python
>>> tracks = client.search('I got a feeling', relation="track")
>>> tracks
[<Track: I Got a Funny Feeling>,
 <Track: I Got a Feeling (Live)>,
 <Track: I Got A Feeling>,
 <Track: Baby, I Got a Feeling>,
 <Track: Babe I Got A Feeling>,
 <Track: I've Got A Feeling I'm Falling>,
 <Track: I've Got a Feeling I'm Falling>,
 <Track: I Got a Feeling in My Body>,
 <Track: I Got A Feeling>,
 <Track: I've Got a Feeling>,
 <Track: I Got A Feeling>,
 <Track: I've Got A Feeling (Remastered 2009)>,
 <Track: I Got A Strange Feeling>,
 <Track: I Got A Feeling>,
 <Track: I Got A Strange Feeling>,
 <Track: I Got a Feeling>,
 <Track: I Got a Feeling>,
 <Track: I Got A Feeling>,
 <Track: I Got a Feeling>,
 <Track: Planet Earth>,
 <Track: I've Got a Feeling I'm Falling>,
 <Track: I've Got That Feeling>,
 <Track: The Grave>,
 <Track: No One Knows You're A Dog>,
 <Track: I've Got A Feeling>]
```

It returns a Python list of `Track`, so you may do a list comprehension to extract the arguments you care about:

```python
>>> [t.id for t in tracks]
[935824782,
 925835792,
 593708742,
 793481362,
 836335702,
 926305492,
 929013222,
 ...]
>>> [t.link for t in tracks]
['https://www.deezer.com/track/935824782',
 'https://www.deezer.com/track/925835792',
 'https://www.deezer.com/track/593708742',
 'https://www.deezer.com/track/793481362',
 'https://www.deezer.com/track/836335702',
 'https://www.deezer.com/track/926305492',
 'https://www.deezer.com/track/929013222',
 'https://www.deezer.com/track/860316722',
 ...]
```

You should be able to access [all the fields documented in the Track object](https://developers.deezer.com/api/track) from the REST API, even more complex ones, like artists:

```python
>>> [t.artist for t in tracks]
[<Artist: Guitar Kelley>,
 <Artist: Cliff Richard>,
 <Artist: Four Tops>,
 <Artist: Elaina Hays>,
 <Artist: David Bach>,
 <Artist: Perry Como>,
 <Artist: Perry Como>,
 ...]
```

Closing this issue, I don't think there is anything to be changed in the library.
