### ISSUE TITLE
Broken on Python 3.7 because async is a reserved keyword

### ISSUE THREAD

**Issue by akumar010** [browniebroke/deezer-python#26]
async is now a reserved keyword in Python 3.7, so async.py needs to be renamed to work in Python 3.7 and newer.

**Comment by browniebroke** [comment]
Thanks for the report! This is indeed a problem, I accept a pull request helping with this, we can start by adding Python 3.7 to the build matrix and then do the rename. I don't think we can provide backwards compatibility for that, so I'll bump the major version to signify a potential breaking change in the API.

**Comment by horstmannmat** [comment]
Can I get this?

**Comment by browniebroke** [comment]
Sure, I think we need to rename this module to something else. I have a preference for `asynchronous`.

**Comment by browniebroke** [comment]
Fixed in #28
