### ISSUE TITLE
Simplify responses mocking

### ISSUE THREAD

**Issue by browniebroke** [browniebroke/deezer-python#38]
The mocking of API responses is built on top of `requests-mock` but the capture of responses is a bit homegrown and it would be good to simplify it. The `vcr.py` library with the `pytest-vcr` look promising:

* https://vcrpy.readthedocs.io
* https://pytest-vcr.readthedocs.io

Note that the local path for the response files should work on Unix (path separator `/`) and Windows (path separator `\`).

**Comment by jnth** [comment]
I played with `vcr.py` theses days and it's a great tool. I can update all tests in my spare time if you're interested.

**Comment by browniebroke** [comment]
Of course, pull requests are more than welcome
