### ISSUE TITLE
Replace usages of `Client.get_object` by `Client.request`

### ISSUE THREAD

**Issue by browniebroke** [browniebroke/deezer-python#383]
Most of the client methods use the `get_object` method internally:

https://github.com/browniebroke/deezer-python/blob/59b0f578127a99622632f51359ba88cc23dcaa1b/deezer/client.py#L156-L174

In #379, the `request` method was added:

https://github.com/browniebroke/deezer-python/blob/59b0f578127a99622632f51359ba88cc23dcaa1b/deezer/client.py#L129-L154

They are very similar, but the `request` method is more versatile, we should aim to migrate all usages to the latter and eventually delete the `get_object` method.

**Comment by deepakdinesh1123** [comment]
Hi, can I take this issue?

**Comment by browniebroke** [comment]
Feel free to take it, yes, but it might involve a good amount of repetitive changes.

Also, I realised that the 2 methods raise a slightly different exception in case of error so this would be a breaking change that will require a major version bump. We need to mark this change as such as explained in the [conventioanl commits](https://www.conventionalcommits.org) spec.
