### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by browniebroke** [browniebroke/deezer-python#39]
With the Python 2 EOL approaching for January 2020, let's remove support for it in this project:

- Remove Python 2.7 from CIs configs
- Remove `__future__` imports
- Remove `# -*- coding: utf-8` comments in Python files
- Remove usages of `six`, replace by built-in Python 3 versions
- Remove dependency on `six` in setup.py & update throve classifiers
- Add [`python_requires` to setup.py](https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords) to specify minimum version of Python (see also [PEP 345](https://www.python.org/dev/peps/pep-0345/#requires-python) and [PEP 440](https://www.python.org/dev/peps/pep-0440/)). Django [implements this](https://github.com/django/django/blob/1835563ab8a1da949a35316d16989236ac585c6c/setup.py#L72).
- Add a breaking change notice in the changelog
- Update documentation

Finally, this will cause a major version bump, meaning v1 of this lib.

**Comment by hugovk** [comment]
Please see PR #41.
