### ISSUE TITLE
Pagination on a search result

### ISSUE THREAD

**Issue by emmanuelvargas** [browniebroke/deezer-python#416]
Hello,

sorry if it's not the good place to ask this but I didn't find anything on the documentation about it.

I'm a bit lost how to have more than 100 results in a search

how work the pagination with a search result?

Thank in advance

**Comment by browniebroke** [comment]
You can iterate through the results using the `limit` and `index` keyword arguments of the search function:

```python
from deezer import Client

cli = Client()
# default search: fetch the first results with the default length (25)
cli.search("Black Eyed Peas")

# fetch the first results with the with a page length of 50
cli.search("Black Eyed Peas", limit=50)

# fetch 20 results, starting from the one at index 21
cli.search("Black Eyed Peas", limit=20, index=21)
```

**Comment by yakuv0** [comment]
> You can iterate through the results using the `limit` and `index` keyword arguments of the search function:
> 
> ```python
> from deezer import Client
> 
> cli = Client()
> # default search: fetch the first results with the default length (25)
> cli.search("Black Eyed Peas")
> 
> # fetch the first results with the with a page length of 50
> cli.search("Black Eyed Peas", limit=50)
> 
> # fetch 20 results, starting from the one at index 21
> cli.search("Black Eyed Peas", limit=20, index=21)
> ```

was that removed later ? getting this error
```
TypeError: search() got an unexpected keyword argument 'limit'
```
cheers

**Comment by browniebroke** [comment]
Yes this was changed when the pagination was reworked to work transparently. See the documentation for and example: https://deezer-python.readthedocs.io/en/stable/usage.html#first-steps

This page links to the section about pagination where it explains in detail the various use cases that were asked about here.

**Comment by yakuv0** [comment]
> Yes this was changed when the pagination was reworked to work transparently. See the documentation for and example: https://deezer-python.readthedocs.io/en/stable/usage.html#first-steps
> 
> This page links to the section about pagination where it explains in detail the various use cases that were asked about here.

Crystal clear, really appreciate it @browniebroke
