### ISSUE TITLE
Only one artist is fetched, when some tracks have multiple artists

### ISSUE THREAD

**Issue by JVT038** [browniebroke/deezer-python#420]
Hi,
So I noticed that this library doesn't support multiple artists for some reason. Or I'm using this library wrong.
Example: [this](https://www.deezer.com/us/track/1425844092) song has two artists: The Kid Laroi and Justin Bieber.
But when I search the track like this:
```python
client = deezer.Client()
search = client.search('Stay', 5)
search[0].artist
# Result: <Artist: The Kid Laroi>
```
Is it possible to get a list of artists? When there's only one artist, there's just one item in the list, like this: `[<Artist: averycoolname>]`, and with multiple artists, this will be returned: `[<Artist: FirstArtist>, <Artist: SecondArtist>]`

**Comment by browniebroke** [comment]
See the [Deezer API docs](https://developers.deezer.com/api/album#infos). An album has a single `artist`. The list of srtists you're looking for is in the `contributors` field, however, this field isn't returning a list of `Artist` instances, it returns the raw list as JSON:

```python
import deezer
client = deezer.Client()
album = client.get_album(680407)
album.contributors
```

Returns:

```python
[{'id': 1020109,
  'name': 'Black Eyed Peas',
  'link': 'https://www.deezer.com/artist/1020109',
  'share': 'https://www.deezer.com/artist/1020109?utm_source=deezer&utm_content=artist-1020109&utm_term=0_1640707159&utm_medium=web',
  'picture': 'https://api.deezer.com/artist/1020109/image',
  'picture_small': 'https://e-cdns-images.dzcdn.net/images/artist/5ee425b0025907ba079cf84095ec1888/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://e-cdns-images.dzcdn.net/images/artist/5ee425b0025907ba079cf84095ec1888/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://e-cdns-images.dzcdn.net/images/artist/5ee425b0025907ba079cf84095ec1888/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://e-cdns-images.dzcdn.net/images/artist/5ee425b0025907ba079cf84095ec1888/1000x1000-000000-80-0-0.jpg',
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/1020109/top?limit=50',
  'type': 'artist',
  'role': 'Main'}]
```

You can iterate over this list and fecth the whole artist instance by ID.

You can do it within your app, or even better, send a PR that to implement a `list_contributors()` method to the `Album` resource.
