### ISSUE TITLE
force US response

### ISSUE THREAD

**Issue by aviwad** [browniebroke/deezer-python#45]
If I use this program with a Japanese VPN, all results (such as track name) in Client().search come in japanese? Is there a way you could force US/english results?

**Comment by browniebroke** [comment]
This is currently not supported by this library, and to be honest I don't know if it's supported by Deezer's API. Will need to look into their docs to find if we can pass a header or something to force a certain localisation.

If you find some info around that, please add them to this issue, or even better, put send me a pull request to implement it, I'll happily review it.

**Comment by browniebroke** [comment]
Yea, it looks like it works. To make this happen, I think we should add the ability to pass any extra headers to use in the `Client` class, not only the `Accept-Language` one.

**Comment by aviwad** [comment]
any update? :sweat_smile:

**Comment by browniebroke** [comment]
Where is your pull request 🤔?

**Comment by aviwad** [comment]
fair enough, I think my update comment might've been annoying. My bad!
