### ISSUE TITLE
Drop Python 3.4

### ISSUE THREAD

**Issue by browniebroke** [browniebroke/deezer-python#46]
Python 3.4 reached [EOL on the 18/03/2019](https://devguide.python.org/devcycle/#end-of-life-branches), it served us well, but it's time to drop support. Files to updates include (at least):

- Remove it from CI configs: `.travis.yml` & `appveyor.yml`
- Remove it from `tox.ini`
- Remove it from `setup.py` classifiers
- Update `python_requires` in `setup.py`
- Check the docs if mentioned anywhere

**Comment by hugovk** [comment]
Please see PR https://github.com/browniebroke/deezer-python/pull/47.
