### ISSUE TITLE
rate_album not working

### ISSUE THREAD

**Issue by prndrbr** [browniebroke/deezer-python#461]
`Client.rate_album` and `Album.rate_album` both fail:

```python
import deezer

client = deezer.Client(access_token='[...]')
client.rate_album(302127, 4)

# OR

album = client.get_album(302127)
album.rate(4)
```

```
Traceback (most recent call last):
  File "rate.py", line 4, in <module>
    client.rate_album(302127, 4)
  File "/deezer/client.py", line 193, in rate_album
    return self.request("POST", f"album/{album_id}", note=note)
  File "/deezer/client.py", line 166, in request
    raise DeezerErrorResponse(json_data)
deezer.exceptions.DeezerErrorResponse: {'error': {'type': 'InvalidQueryException', 'message': 'Unknown path components : /album/302127 for request_method post', 'code': 600}}
```

I guess this API endpoint was removed?

**Comment by browniebroke** [comment]
Well, that's annoying 😞 Indeed, I cannot find this in the API documentation anymore... I'm pretty sure I used the real API to [record the cassette](https://github.com/browniebroke/deezer-python/commit/c8dc771b6c11c927cd599dc88563b9ec6db2f994), so yes, it was probably removed. Unfortunately, I have no "insider" information. 

I wish there was an API doc in a standard format like swagger or something to get alerted of these kind of changes... Looks like the best we can do is follow their Dev Twitter account: https://developers.deezer.com/support
