### ISSUE TITLE
Why documentation is empty?

### ISSUE THREAD

**Issue by orcololo** [browniebroke/deezer-python#50]
initially, I thought the problem was in my browser, but when I went to look at the docs in the source, I realized that there was no documentation available. :(

**Comment by browniebroke** [comment]
I generated the API reference from the code, but it could be better. It's pretty lightly documented, but I wouldn't say it's empty 😄 

The aim was to rely mostly on [the documentation provided by Deezer](https://developers.deezer.com/api) itself and try to mirror their resources. 

I am not affiliated with Deezer at all, and I only maintain this on my free time. I you feel like writing a few paragraphs to get people started more easily, a pull request in more than welcome. The best place for this is a new file in the [`docs/source`](https://github.com/browniebroke/deezer-python/tree/master/docs/source) directory.
