### ISSUE TITLE
Album missing attributes depending on how called

### ISSUE THREAD

**Issue by Truxnell** [browniebroke/deezer-python#530]
I noted the behaviour below trying to extract UPC information.  If i query the Album directly, I can access all the metadata I expect.  However, if i get the album 'second-hand' from a Artist.get_albums() call, i cant access the upc (possible other metadata)

The below is a test case using the album 'The Bitter Truth' (deezer: 217273312) from artist Evanesence (

**Direct Query Album - UPC extracts OK**
```
>>> import deezer
>>> dz = deezer.Client()
>>> dz.get_album(217273312)
<Album: The Bitter Truth>
>>> dz.get_album(217273312).upc
'886447444504'
```

**Indirect query album (i.e. via an artist search) - UPC not present in Album**
```
>>> a=next(dz.get_artist(98).get_albums())
>>> a.id
217273312
>>> a.title
'The Bitter Truth'
>>> a.upc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Album' object has no attribute 'upc'
```

Let me know if this is just user error, i *can* get the metadata with a direct query, however it will incur an extra API call per loop and I honestly expected i would have all the data from the artist.get_albums() search already!

**Comment by browniebroke** [comment]
Yes, this is essentially the same issue as https://github.com/browniebroke/deezer-python/issues/424

Unfortunately, we're limited by what the server returns here, and I don't control that (I'm not affiliated with Deezer). Adding the missing fields to the `get_...` methods isn't an option, but we could make it clearer in this library API that you don't get a full entity.

**Comment by Truxnell** [comment]
Derp, I had a look at the issues and #424's title just didnt sound like it was the same.

Thanks, ill add in a extra call, i had assumed it would have been the same call, but thinking about it, it isnt *quite* the same looking through the API.  Just trying to be API friendly & considering with my code!
