### ISSUE TITLE
AttributeError: 'Episode' object has no attribute 'link'

### ISSUE THREAD

**Issue by andygrunwald** [browniebroke/deezer-python#536]
When using the following code with v5.3.3 of this lib

```python
deezer_client = deezer.Client()
deezer_podcast = deezer_client.get_podcast(3330122)
deezer_episodes = deezer_podcast.get_episodes()

for episode in deezer_episodes:
   print(episode.title)
   print(dir(episode))
   print(episode.link)
```

I get an output like

```
my episode title
['__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_fields', '_fields_parsers', '_parse_release_date', 'as_dict', 'client', 'duration', 'get_paginated_list', 'get_relation', 'id', 'picture', 'podcast', 'release_date', 'title', 'type']
Traceback (most recent call last):
  [...],
  File "/path/to/file.py", line 517, in function_name
    print(episode.link)
AttributeError: 'Episode' object has no attribute 'link'
```

According to [deezer.Episode](https://deezer-python.readthedocs.io/en/stable/api_reference/resources/episode.html#deezer.Episode), this attribute should be available. According to the official deezer docs as well.

As a workaround, I can craft the link myself like `f"https://www.deezer.com/de/episode/{episode.id}"`.

Is this a bug or a mistake on my side?

**Comment by browniebroke** [comment]
Hey, thanks for the report. This is the same problem as described in #424 and #530. The Deezer API doesn't return the same fields when accessing [a resource directly](https://developers.deezer.com/api/episode) vs listing [it as subresource](https://developers.deezer.com/api/podcast/episodes).

I cannot change what the server returns (I'm not affiliated with Deezer) but I'd like to make this a bit more transparent from the client. Right now, there is no other way than fetching the whole episode with a separate API call.

**Comment by browniebroke** [comment]
Fixed in the latest release https://github.com/browniebroke/deezer-python/releases/tag/v5.4.0

**Comment by browniebroke** [comment]
Actually I saw how you were using this in your project and it inspired me to improve that feature. The library can now avoid extra API call when the missing attribute can be infered from the existing fields. I've implemented this for `Episode.link` so you should have the best of both worlds: the attribute will be present without extra API call.

This is released in https://github.com/browniebroke/deezer-python/releases/tag/v5.5.0

**Comment by andygrunwald** [comment]
Nice! Thanks a lot @browniebroke
