### ISSUE TITLE
Usage example from README not works

### ISSUE THREAD

**Issue by spvkgn** [browniebroke/deezer-python#59]
Am i do something wrong in this?
```
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deezer
>>> client = deezer.Client()
>>> client.get_album(12).title
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Resource' object has no attribute 'title'
```

**Comment by browniebroke** [comment]
Thanks for the report, it looks like a bug! I think it worked at some point, but it's obviously not working anymore.

It's probably that the client methods aren't returning the proper classes, but the base `Resource` one. If you search and get relation from a `Track` this attribute is present, example:

```python
> ipython
Python 3.6.8 (default, Jan 19 2019, 12:07:51)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deezer

In [2]: client = deezer.Client()

In [3]: client.search('Discovery')[0]
Out[3]: <Track: One More Time>

In [4]: client.search('Discovery')[0].get_album()
Out[4]: <Album: Discovery>

In [5]: client.search('Discovery')[0].get_album().title
Out[5]: 'Discovery'
```

However, when trying to get the album directly, the type is a `Resource`, not an `Album`:

```
> ipython
Python 3.6.8 (default, Jan 19 2019, 12:07:51)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deezer

In [2]: client = deezer.Client()

In [3]: client.get_album(12)
Out[3]: <deezer.resources.Resource object at 0x1032704e0>
```

There is a similar problem when trying to get other object types, like artists, track, etc...

**Comment by nrebena** [comment]
The problem here is that the album 12 does not exist, and the method default to returning Ressource type.
```
https://api.deezer.com/album/12
{"error":{"type":"DataException","message":"no data","code":800}}
```

So this issue is more about error handling.
There are many ways one can go there:
* This is not a bug, there is effectively no title to be returned. Let's change the README to an existing album id
* Raise an error when getting an error from the API
* Other...

**Comment by browniebroke** [comment]
Good find! Agree that the error should be made explicit, and raise an exception. Also we should not default to Resource type when no suitable resource type is found.

Also the README should be updated too I think.

**Comment by browniebroke** [comment]
@all-contributors please add @spvkgn for bug

**Comment by browniebroke** [comment]
@all-contributors please add @spvkgn for bug
