### ISSUE TITLE
Enable bandit on Fussyfox checks

### ISSUE THREAD

**Issue by browniebroke** [browniebroke/deezer-python#62]
We run [Fussyfox](https://github.com/FussyFox/) on CI, but currently [Bandit](https://github.com/PyCQA/bandit) is disabled:

https://github.com/browniebroke/deezer-python/blob/400df875fa54c1941475fe4932b23d55c0b84cac/.fussyfox.yml#L1

This would be nice to enable this check, but first we need to fix the existing issues we have. To do so:

1. Uncomment the line above
2. Open a pull request, which should enable this check and show the problems to fix
3. Update the code to fix the issues or disable checks if inappropriate

Stretch goal: also provide a way to run bandit locally, via tox.

**Comment by sgaist** [comment]
Hi,

I'd like to work on this one :-)
