### ISSUE TITLE
`Client.search()` returns an empty paginated list

### ISSUE THREAD

**Issue by sortedcord** [browniebroke/deezer-python#651]
Followed the installation steps for this package but for some reason its always returning an empty paginated list.

```py
import deezer

client = deezer.Client()
print(client.get_album(680407).title)
print(client.search('Daft Punk'))
```

Output - 
```
'Monkey Business'
<PaginatedList []>
```

So apparently get_album works but search doesn't. Am I missing something here?

**Comment by sortedcord** [comment]
I tried putting in the access token and it works. So I suppose for searching, you need authentication

**Comment by browniebroke** [comment]
Weird, I just tried again now and it worked fine without the need for authentication...
