### ISSUE TITLE
get_user_playlists  missing

### ISSUE THREAD

**Issue by jonbng** [browniebroke/deezer-python#681]
Hi! I love this lib and im currently using it to integrate deezer into music assistant.
But i have a problem. The `get_user_albums` works great but i would also love to be able to use `get_user_playlists`
Is there a reason this dosnt exists or is it just not implemented yet? Looking at the api docs it looks like its possible
Thanks,
Jonathan

**Comment by browniebroke** [comment]
If that's possible in the official Deezer API docs, it might be just that it wasn't implemented yet. I don't dedicate too much energy into this project, however I do accept contributions to cover anything missing, as long as it's tested and documented by the official Deezer docs.

Let me know if you need any guidance to get started, our contributing guide should be enough to get you started. If that's not the case, let me know and I'll fill in the gaps! 

Thanks for the idea.

**Comment by Un10ck3d** [comment]
Ok 👍🏼 I will definitely implement it at some point then
