### ISSUE TITLE
How a get more than 400 song from a playlist?

### ISSUE THREAD

**Issue by EricRibs** [browniebroke/deezer-python#73]
I tried to get the songs from a big playlist but
 only 400 songs are returned. Is there any way to get all the songs from a large playlist?
![rsz_12019-11-26-105046_1920x1080_scrot](https://user-images.githubusercontent.com/57811230/69639337-19315600-103b-11ea-80ee-dfdfe4f13e31.png)
The playlist link is deezer.com/playlist/5308276702

**Comment by browniebroke** [comment]
Can you please avoid posting screenshot? It's not possible to copy/paste from an image. Making a code snippet is a lot more useful.

I can't remember if we have a proper pagination in the client or if it's a limitation of the Deezer API itself. 

https://github.com/browniebroke/deezer-python/blob/2373bf69d52df50a9b64db49717ee36a06799191/deezer/resources.py#L269-L270

You can try to do `playlist.iter_relation('tracks')` maybe?

**Comment by EricRibs** [comment]
Sorry about the image. I tried how you said and  it worked well. Thanks for you help.
```python3
import deezer

client = deezer.Client()
playlist = client.get_playlist(5308276702)
j = 0
for i in playlist.iter_relation('tracks'):
     j+=1
print(j)
```
